# Generated by Django 2.1.4 on 2018-12-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='gender',
            field=models.BooleanField(choices=[(False, 'Kobieta'), (True, 'Mężczyzna')], default=False),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='image',
            field=models.ImageField(default='default.png', upload_to='avatars/'),
        ),
    ]
