# Generated by Django 2.1.4 on 2018-12-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181224_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='image',
            field=models.ImageField(upload_to='avatars/'),
        ),
    ]
