# Generated by Django 2.1.4 on 2018-12-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.IntegerField(choices=[(1, 'Szkic'), (2, 'Nieopublikowane'), (3, 'Opublikowane')], default=1),
        ),
    ]
